# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

Exception: File `'initialise.py'` not found.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.21.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
nullArray = np.full(10, np.nan)
nullArray

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
nullArray.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
nullArray[4] = 1
nullArray

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
rangeNum = np.arange(10,50)
rangeNum

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
rangeNum[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
arr = [1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.rand(3,3,3)

array([[[0.79827202, 0.96707739, 0.05677021],
        [0.14551588, 0.49836677, 0.28068178],
        [0.85473229, 0.49223538, 0.52880669]],

       [[0.90681032, 0.04309912, 0.00585871],
        [0.59268365, 0.67047521, 0.16154626],
        [0.08159   , 0.42375448, 0.0552441 ]],

       [[0.28233441, 0.4943828 , 0.78205563],
        [0.44119655, 0.1431642 , 0.13851538],
        [0.32643882, 0.94369409, 0.07872387]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
rand = np.random.rand(10,10)
print(rand)
print()
print()
print('minimum: ',np.min(rand))
print('maximum: ',np.max(rand))

[[0.44604618 0.24149685 0.704031   0.10775246 0.85278164 0.76032905
  0.87791594 0.49305499 0.69674519 0.10846033]
 [0.97273832 0.6239369  0.96316322 0.81632941 0.22921446 0.61165705
  0.30349368 0.11843125 0.70787788 0.05476942]
 [0.93170588 0.24815171 0.50029465 0.87465817 0.22085566 0.95446193
  0.6548303  0.7249402  0.71794857 0.92489171]
 [0.11529274 0.59864199 0.13424201 0.53612075 0.17821937 0.70904476
  0.31998715 0.74800129 0.54816172 0.91753725]
 [0.06787298 0.009686   0.61702332 0.65037272 0.16119637 0.72587231
  0.84869897 0.28488378 0.30892639 0.55697379]
 [0.18980474 0.70553654 0.81422084 0.76050793 0.94796586 0.95833712
  0.04110006 0.45673775 0.21702917 0.40864197]
 [0.4104236  0.2044873  0.8403848  0.06512721 0.62609542 0.14098138
  0.25140419 0.32920169 0.94047018 0.72999746]
 [0.4487011  0.68539929 0.54796921 0.2470344  0.55540676 0.61796003
  0.66757654 0.88251208 0.21178166 0.50246324]
 [0.81327917 0.42748441 0.68482247 0.87690792 0.70780585 0.05091397
  0.4288828 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
v30 = np.random.rand(30)
print(v30)
print()
print('mean: ',np.mean(v30))

[0.90775319 0.81720161 0.31148614 0.16350249 0.86733583 0.91444703
 0.70058472 0.87346419 0.7398882  0.37143135 0.46216554 0.2424147
 0.31620381 0.08115963 0.32564239 0.8696062  0.17006566 0.67775341
 0.53522098 0.75523598 0.31289505 0.70936921 0.23697417 0.35220817
 0.34654287 0.285364   0.2397878  0.02734227 0.09988391 0.0971441 ]

mean:  0.46033582003014656


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr2 = np.full((5,5),1)
print(arr2)
arr2[1:-1, 1:-1] = 0
print()
print()
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
# arr, index, val, axis
r = np.insert(arr2, [0,len(arr)-1], 0,0)
np.insert(r,[0,len(r)-2],0,1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

- nan
- True
- True
- nan
- True
- False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
k=[1,2,3,4,5]
np.eye(5,k=-1)*k

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
arr3 = np.array([0,1])
np.tile(arr3, (8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
n = np.random.randint(0,101,(6,7,8))
# np.ar
n.sort()
np.where(len(n)==100)

(array([], dtype=int64),)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
np.tile([0,1],(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
arr4 = np.random.randint(1,100,(5,5))
normalizedArr = ((arr4 - np.min(arr4)))/ (np.max(arr4) - np.min(arr4))
normalizedArr

array([[0.89247312, 0.40860215, 0.31182796, 0.90322581, 0.31182796],
       [0.90322581, 0.92473118, 0.86021505, 0.30107527, 0.8172043 ],
       [0.7311828 , 0.66666667, 0.22580645, 0.97849462, 0.        ],
       [1.        , 0.89247312, 0.03225806, 0.11827957, 0.07526882],
       [0.11827957, 0.97849462, 0.53763441, 0.69892473, 0.90322581]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [23]:
matrix1 = np.random.randint(1,1000,(5,3))
matrix2 = np.random.randint(1,1000,(3,2))
print(matrix1)
print()
print(matrix2)
print(np.product(matrix1,matrix2))

[[552 909 611]
 [225 621 772]
 [444  60 500]
 [484 110 840]
 [757 974 738]]

[[432 917]
 [133  80]
 [853 320]]


TypeError: only integer scalar arrays can be converted to a scalar index

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [24]:
arr5 = np.random.randint(0,11,10)
print(arr5)
print(np.where((arr5.any()>3 and arr5.any()<8)))

[ 3  0  5  3  3  3  4  3  4 10]
(array([], dtype=int64),)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

- first: Error

- second: (0+ -1), (1+ -1), (2+ -1), (3+ -1), (4+ -1)
=   -1,   0,        1,        2,        3

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- legal are
- first
- third
- forth
- fifth

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

- np.inf
- np.inf
- 0.0

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [25]:
arr6 = np.random.randint(0, 20,20)
arr7 = np.random.randint(0, 20,20)
print(arr6)
print()
print(arr7)
print()
np.intersect1d(arr6, arr7)

[15  1 14 10 10 14 10 13 14 16  8  8 11 15  6 13 14 10  3  8]

[14 14 17 13 13  2  8  5 17 10  1 15 16 19  5 13  2  4  2 19]



array([ 1,  8, 10, 13, 14, 15, 16])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [26]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [27]:
today = np.datetime64('today')
print('today: ', today)
print()


yesterday = today - 1
print('yesterday: ', yesterday)
print()


tomorrow = today + 1
print('tomorrow: ', tomorrow)

today:  2024-02-14

yesterday:  2024-02-13

tomorrow:  2024-02-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [28]:
np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [29]:
a = np.random.randint(1,100,10)
b = np.random.randint(1,100,10)
print('a: ', a)
print('b: ', b)
a = ((a + b) * (-a / 2))
print('computed equation: ', a)

a:  [99 29 73 45 42 75 21 97 27 95]
b:  [51 30  5 69  9 35 23 96 54 17]
computed equation:  [-7425.   -855.5 -2847.  -2565.  -1071.  -4125.   -462.  -9360.5 -1093.5
 -5320. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [30]:
randnums = np.random.rand(20)*100+85
print(randnums)
print()
print(np.int32(randnums))
import re
re.split('\.| |[|]',str(randnums))

[132.02139378 112.77540122  96.62511113 123.47919341 117.01276713
  97.98648448 124.48357947 184.5831078  175.70669955 127.95343399
 170.78717005 158.50517149 180.22292474 115.70630379 164.76874577
 141.48284515  89.95123454  87.42293074 163.27441772 147.78595536]

[132 112  96 123 117  97 124 184 175 127 170 158 180 115 164 141  89  87
 163 147]


['[132',
 '02139378',
 '112',
 '77540122',
 '',
 '96',
 '62511113',
 '123',
 '47919341',
 '117',
 '01276713\n',
 '',
 '97',
 '98648448',
 '124',
 '48357947',
 '184',
 '5831078',
 '',
 '175',
 '70669955',
 '127',
 '95343399\n',
 '170',
 '78717005',
 '158',
 '50517149',
 '180',
 '22292474',
 '115',
 '70630379',
 '164',
 '76874577\n',
 '141',
 '48284515',
 '',
 '89',
 '95123454',
 '',
 '87',
 '42293074',
 '163',
 '27441772',
 '147',
 '78595536]']

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [31]:
np.tile(np.arange(0,5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [32]:
def generate10Nums():
    print(np.random.randint(0,10, 10))
generate10Nums()

[0 8 6 1 3 0 8 4 5 7]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [33]:
np.arange(0.01,0.11,0.01)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [34]:
sortedarr = np.sort(np.random.randint(0,100,10))
sortedarr

array([ 4, 14, 34, 45, 46, 50, 62, 68, 84, 95])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [35]:
np.einsum(*+,sortedarr)

SyntaxError: invalid syntax (2950588351.py, line 1)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [36]:
A = np.random.randint(0,100)
B = np.random.randint(0,100)
A == B

False

#### 43. Make an array immutable (read-only) (★★☆)

In [37]:
s = set([1,2,3])
s

{1, 2, 3}

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [40]:
x = 10
y = 2
# p(x, y)
# p(10, 2)

# p(r, ceta)
# p(r, ceta)?

# r = x**2 + y**2


r = (x ** 2) + (y ** 2)
print('r = ', r)


ceta = np.arctan(y / x)
print('ceta = ', ceta)

r =  104
ceta =  0.19739555984988078


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [38]:
randint10 = np.random.randint(0,100,10)
print(randint10)
indexOfMax = np.argmax(randint10)
print(indexOfMax)
randint10[indexOfMax] = 0
print(randint10)

[57 41 82 85 68 18 77 24 92 64]
8
[57 41 82 85 68 18 77 24  0 64]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [45]:
np.random.randint(0,100, (1,1))

array([[77]])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [56]:
x = np.random.randint(1,1000,(8,8))
y = np.random.randint(1,1000,(8,8))


print('x ', x)
print()
print()
print()
print('y ', y)
print()
print()
print()



c = (1 / (x.copy() - y.copy()))


print('c', c)

x  [[326 515 288 485 150 360  68 667]
 [454 877 901 169 859 198 704 931]
 [  2 206 760 633 543 943 245 452]
 [577 403 993 284 883 435 945 306]
 [  8 443 688 965  25 195 944 281]
 [ 89 391 300 841 451 342 585 150]
 [403 316 100 355 345 910  20 909]
 [ 84  35 104 914 983 315 533 497]]



y  [[590 843 980 748 191 586 530  19]
 [336 114 948 736 517 975 835 696]
 [855  52 646  46 138 867 662 317]
 [582 975 436 235 484 474 668 373]
 [904 726 326 190 673  51 563  60]
 [602 442 932 213  25 483 288 205]
 [997 595 174 783 971 368  13 195]
 [232 149 375 980 117   6 169 649]]



c [[-0.00378788 -0.00304878 -0.00144509 -0.00380228 -0.02439024 -0.00442478
  -0.0021645   0.00154321]
 [ 0.00847458  0.00131062 -0.0212766  -0.00176367  0.00292398 -0.001287
  -0.00763359  0.00425532]
 [-0.00117233  0.00649351  0.00877193  0.00170358  0.00246914  0.01315789
  -0.00239808  0.00740741]
 [-0.2        -0.00174825  0.00179533  0.02040816  0.00250627 -0.02564103
   0.00361011 -0.01492537]
 [-0.00111607 -0.00353

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [57]:
np.min(['m','a'])

TypeError: cannot perform reduce with flexible type

#### 49. How to print all the values of an array? (★★☆)

In [66]:
import sys
arr49 = np.random.randint(1,100, 10)
np.set_printoptions(threshold=sys.maxsize)
print(arr49)

[85 40 37  4 27 96 13 89 16  9]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)